import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Web3Modal } from '../context/Web3Modal'
import "./globals.css";
import { DataProvider } from "@/context/DataProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3Modal>
          <DataProvider>
            {children}
          </DataProvider>
        </Web3Modal>
      </body>
    </html>
  );
}
